spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/justdb
    username: postgres
    password: pass1234
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop